# ----
# Site

title: cme dev style guide
url: "https://smart-pilot.cloudvent.net"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: c a u g ht my e y e dev style guide
author:
  name: mark l chaves
  email: mark@marklchaves.com
  twitter: marklchaves # twitter username without the @ symbol
social:
  name: cme dev style guide
  links:
    - https://github.com/marklchaves/cme-dev-style-guide

# -----
# Build

timezone: Etc/UTC+8

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
